server:
    port: 8080

spring:
    profiles:
        active: prod
    data:
        mongodb:
            uri: mongodb://ignacioSuay:H0mersit0!@ds039281.mongolab.com:39281/fcetests
            port: 39281
            host: ds039281.mongolab.com
            database: fcetests
            username: ignacioSuay
            password: H0mersit0!

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: true

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: firstCertificateTests


